### ISSUE TITLE
ユーザー登録時に「未設定」のプロジェクト・コンテキストを作成

### ISSUE THREAD

**Issue by Soh1121** [Soh1121/ToDoRo#116]
## 🎉 Goal

- [x] ユーザー登録すると「未設定」というプロジェクト・コンテキストが登録される

## 📝 Overview

ユーザー登録とともにユーザーのプロジェクト・コンテキストの紐付けがないものが存在しないように「未設定」を作成する

## 📆 Schedule

- 2020年11月7日中にClose

## 📎 Tasks

- [x] ユーザー登録処理に「未設定」プロジェクトを作成
- [x] ユーザー登録処理に「未設定」コンテキストを作成
