### ISSUE TITLE
タイマー動作中のタスク切り換えを実装

### ISSUE THREAD

**Issue by Soh1121** [Soh1121/ToDoRo#329]
## 🎉 Goal

- [x] タイマー動作中に別のタスクをスタートしようとするとダイアログが表示される
- [x] ダイアログ外部をクリックするとダイアログを閉じる
- [x] 「現在のタスクを進める」をクリックすると、現在のタスクのタイマー画面に遷移する
- [x] 「新しいタスクを行う」をクリックすると、現在のタスクを一時停止し、新しいタスクをセットしたタイマー画面に遷移する
- [x] 「キャンセル」をクリックすると、ダイアログを閉じる

## 📝 Overview

- タイマー動作中に別のタスクの再生ボタンを押すと、動作がおかしくなる
- そこで、別のタスクを開始しようとした際の処理をきちんと整理する

## 📆 Schedule

- 2021年6月13日（日）中にClose

## 📎 Tasks

- [x] キャンセルボタンをクリックしたらダイアログを閉じる
- [x] ダイアログ外をクリックしたらダイアログを閉じる
- [x] 「現在のタスクを進める」をクリックしたら、現在のタスクのタイマー画面に遷移
- [x] 「新しいタスクを行う」をクリックしたら、現在のタスクのタイマーを一時停止
- [x] 現在のタスクのタイマーを一時停止したら、新しいタスクのタイマーをセットして画面を遷移する
- [x] リファクタリング
