### ISSUE TITLE
静的解析ツールLarastanの導入

### ISSUE THREAD

**Issue by Soh1121** [Soh1121/ToDoRo#5]
## 🎉 Goal

Larastanが走ってコード解析が行われる

## 📝 Overview

静的解析ツールとしてLarastanを導入する

## 📖 Reference

- [Larastan](https://github.com/nunomaduro/larastan)

## 📆 Schedule

2020/06/05（金）までにClose

## 📎 Tasks

- [x] `Larastan` のインストール： `docker-compose exec web composer require --dev nunomaduro/larastan`
- [x] `phpstan.neon` をアプリケーションのルートディクトリ( `web/`)に作成
- [x] `docker-compose exec web ./vendor/bin/phpstan analyse` でコードを解析
- [x] エラー修正
    - `web/app/Http/Middleware/Authenticate.php` の `redirectTo` の返り値に `null` を追加
