### ISSUE TITLE
認証による要素の出し分け

### ISSUE THREAD

**Issue by Soh1121** [Soh1121/ToDoRo#51]
## 🎉 Goal

- [x] ログイン中の場合は「登録・ログイン」ボタンを非表示
- [x] ログイン中の場合は「メニュー」ボタンを表示
- [x] ログアウト中の場合は「登録・ログイン」ボタンを表示
- [x] ログアウト中の場合は「メニュー」ボタンを非表示

## 📝 Overview

認証状態によってナビゲーションバーの要素を出し分ける

## 📖 Reference (optional)

- [Vue + Vue Router + Vuex + Laravelで写真共有アプリを作ろう (7) 認証機能とVuex Part.2 | Hypertext Candy](https://www.hypertextcandy.com/vue-laravel-tutorial-authentication-part-4/#%E3%82%B9%E3%83%86%E3%83%BC%E3%83%88%E3%81%AE%E5%80%A4%E3%81%AB%E3%82%88%E3%82%8B%E8%A6%81%E7%B4%A0%E3%81%AE%E5%87%BA%E3%81%97%E5%88%86%E3%81%91)

## 📆 Schedule (optional)

- 2020年8月16日までにClose

## 📎 Tasks (optional)

- [x] ゲッターの追加
- [x] ナビゲーションバーの要素の出し分け
